# Generated by Django 5.1.4 on 2025-05-25 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseInterviewer', '0003_userscores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userscores',
            name='rightAnswers',
        ),
        migrations.RemoveField(
            model_name='wronganswer',
            name='questionsID',
        ),
        migrations.RemoveField(
            model_name='userscores',
            name='wrongAnswers',
        ),
        migrations.RenameField(
            model_name='nontechquestions',
            old_name='questionsID',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='technicalquestions',
            old_name='questionsID',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='userscores',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='userscores',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userscores',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='baseInterviewer.previousquestions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userscores',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=1000)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseInterviewer.previousquestions')),
            ],
        ),
        migrations.AddField(
            model_name='userscores',
            name='answer_text',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='baseInterviewer.answer'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RightAnswer',
        ),
        migrations.DeleteModel(
            name='WrongAnswer',
        ),
    ]
