# Generated by Django 6.0.4 on 2026-05-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseInterviewer", "0005_previousleetcode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userscores",
            name="answer_text",
        ),
        migrations.RenameField(
            model_name="previousquestions",
            old_name="questionID",
            new_name="id",
        ),
        migrations.RemoveField(
            model_name="previousquestions",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="userscores",
            name="is_correct",
        ),
        migrations.RemoveField(
            model_name="userscores",
            name="user",
        ),
        migrations.AddField(
            model_name="previousquestions",
            name="isCorrect",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="previousquestions",
            name="system_answer",
            field=models.CharField(default="test", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userscores",
            name="score",
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Answer",
        ),
    ]
